# Documentation Sync Trigger for External Repositories
# 
# This workflow triggers the main website rebuild when docs are updated.
# The main site's build process automatically syncs docs, so we just need to trigger a deploy.
#
# Copy this file to .github/workflows/docsync.yml in your external repository.

name: Trigger documentation sync

on:
  # Trigger on all pushes to main (since docs could be anywhere)
  push:
    branches: [ main ]
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  trigger-docsync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger website rebuild
      run: |
        if [ -n "${{ secrets.RENDER_DEPLOY_HOOK }}" ]; then
          echo "Triggering website rebuild..."
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
          echo "Website rebuild triggered successfully"
        else
          echo "RENDER_DEPLOY_HOOK not configured, skipping rebuild trigger"
        fi
